services:
  alist:
    image: xhofe/alist:v3.56.0
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - alist-data:/opt/alist/data
      
volumes:
  alist-data: