services:
  answer:
    image: apache/answer:1.7.1
    restart: always
    ports:
      - '80'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - answer-data:/data
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: answer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  answer-data:
  db-data:
