[variables]
main_domain = "${domain}"
wg_password = "${password:32}"

[config]
[[config.domains]]
serviceName = "wg-easy"
port = 51821
host = "${main_domain}"

[config.env]
INIT_HOST = "${main_domain}"
INIT_USERNAME = "wg-admin"
INIT_PASSWORD = "${wg_password}"
