[variables]
main_domain = "${domain}"
db_password = "${password}"
db_user = "postiz"
db_name = "postiz"
jwt_secret = "${base64:32}"

[config]
mounts = []

[[config.domains]]
serviceName = "postiz-app"
port = 5_000
host = "${main_domain}"

[config.env]
POSTIZ_HOST = "${main_domain}"
DB_PASSWORD = "${db_password}"
DB_USER = "${db_user}"
DB_NAME = "${db_name}"
JWT_SECRET = "${jwt_secret}"

EMAIL_HOST = ""
EMAIL_PORT = "587"
EMAIL_SECURE = "false"
EMAIL_USER = ""
EMAIL_PASS = ""

CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_ACCESS_KEY = ""
CLOUDFLARE_SECRET_ACCESS_KEY = ""
CLOUDFLARE_BUCKETNAME = ""
CLOUDFLARE_BUCKET_URL = ""
CLOUDFLARE_REGION = ""

BEEHIIVE_API_KEY = ""
BEEHIIVE_PUBLICATION_ID = ""
DISCORD_CLIENT_ID = ""
DISCORD_CLIENT_SECRET = ""
DISCORD_BOT_TOKEN_ID = ""
DRIBBBLE_CLIENT_ID = ""
DRIBBBLE_CLIENT_SECRET = ""
FACEBOOK_APP_ID = ""
FACEBOOK_APP_SECRET = ""
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
LINKEDIN_CLIENT_ID = ""
LINKEDIN_CLIENT_SECRET = ""
MASTODON_CLIENT_ID = ""
MASTODON_CLIENT_SECRET = ""
PINTEREST_CLIENT_ID = ""
PINTEREST_CLIENT_SECRET = ""
REDDIT_CLIENT_ID = ""
REDDIT_CLIENT_SECRET = ""
SLACK_ID = ""
SLACK_SECRET = ""
SLACK_SIGNING_SECRET = ""
THREADS_APP_ID = ""
THREADS_APP_SECRET = ""
TIKTOK_CLIENT_ID = ""
TIKTOK_CLIENT_SECRET = ""
X_API_KEY = ""
X_API_SECRET = ""
X_CLIENT = ""
X_SECRET = ""
YOUTUBE_CLIENT_ID = ""
YOUTUBE_CLIENT_SECRET = ""
