services:
  actualbudget:
    image: actualbudget/actual-server:latest
    restart: unless-stopped
    environment:
      # See all options at https://actualbudget.org/docs/config
      - ACTUAL_PORT=5006
    volumes:
      - actual-data:/data

volumes:
  actual-data:
