services:
  calcom:
    image: calcom/cal.com:v6.1.0
    restart: always
    environment:
      - NEXT_PUBLIC_WEBAPP_URL=http://${CALCOM_HOST}
      - NEXTAUTH_URL=http://${CALCOM_HOST}/api/auth
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
      - CALCOM_TELEMETRY_DISABLED=1

      - DATABASE_URL=postgres://postgres:password@postgres:5432/db
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - DATABASE_URL=postgres://postgres:password@postgres:5432/db
    volumes:
      - calcom-data:/var/lib/postgresql/data

volumes:
  calcom-data:
